name: spooky_flutter_app
description: A spooky Halloween-themed Flutter app with sound effects.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.18
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/sounds/
    - assets/images/
